[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_lib"
crate-type = ["lib", "cdylib"]

[dependencies]
android_logger = "0.11.1"
log = "0.4.17"
jni = "0.20.0"
once_cell = "^1"
